development:
  dialect: postgres
  database: scaruffi_dev
  user: {{env "PG_USER"}}
  password: {{env "PG_PASSWORD"}}
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: scaruffi_test
  user: {{env "PG_USER"}}
  password: {{env "PG_PASSWORD"}}
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: scaruffi_prod
  user: {{env "PG_USER"}}
  password: {{env "PG_PASSWORD"}}
  host: 127.0.0.1
  pool: 5